[package]
name = "nse"
version = "0.1.0"
authors = ["Wolfgang Rumpler <contact@iflow.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7" # multithreading library
mopa = "0.2.2"

#winit = "0.20.0-alpha5"
winit = "0.21.0"

ash = "0.29.0"
ash-window = "0.1.0"

vulkano = "0.17.0"
vulkano-win = "0.17.0"
vulkano-shaders = "0.17.0"

cgmath = "0.17.0"

gfx = "0.18.2"
imgui = "0.3.0"
imgui-winit-support = "0.3.0"
imgui-gfx-renderer = "0.3.0"