[package]
name = "nse"
version = "0.1.0"
authors = ["Wolfgang Rumpler <contact@iflow.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7" # multithreading library
